---
# site.yml

############################
# Play 1: Configure Router #
############################
- name: Configure router for routing + NAT (+ DHCP if desired)
  hosts: router
  become: true
  gather_facts: true

  vars:
    enable_dhcp: false

  pre_tasks:
    - name: Detect router LAN IPv4 on {{ lan_interface }}
      ansible.builtin.command: "ip -4 -o addr show dev {{ lan_interface }}"
      register: lan_ip_cmd
      changed_when: false

    - name: Parse router LAN IPv4 address
      ansible.builtin.set_fact:
        router_lan_ip: "{{ (lan_ip_cmd.stdout | regex_search('inet\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)', '\\1')) | default('') }}"

    - name: Fail if router LAN IP is not set
      ansible.builtin.fail:
        msg: "Please assign a static IP to {{ lan_interface }} in {{ lan_subnet }}/{{ lan_netmask }} first."
      when: router_lan_ip == ""

  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ ['iptables', 'iptables-persistent', 'netfilter-persistent'] + (enable_dhcp | ternary(['dnsmasq'], [])) }}"
        state: present
      notify: Save iptables

    - name: Enable IPv4 forwarding now
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: true

    - name: Flush iptables (nat + forward chains)
      ansible.builtin.shell: |
        iptables -F
        iptables -t nat -F

    - name: Allow forwarding LAN -> WAN
      ansible.builtin.command: >
        iptables -A FORWARD -i {{ lan_interface }} -o {{ wan_interface }} -j ACCEPT
      changed_when: true

    - name: Allow forwarding WAN -> LAN (established/related only)
      ansible.builtin.command: >
        iptables -A FORWARD -i {{ wan_interface }} -o {{ lan_interface }} -m state --state ESTABLISHED,RELATED -j ACCEPT
      changed_when: true

    - name: NAT masquerade on WAN
      ansible.builtin.command: >
        iptables -t nat -A POSTROUTING -o {{ wan_interface }} -j MASQUERADE
      changed_when: true
      notify: Save iptables

    - name: Persist iptables
      ansible.builtin.shell: netfilter-persistent save
      changed_when: false

    - name: Configure dnsmasq for DHCP (if enabled)
      when: enable_dhcp
      block:
        - name: Create dnsmasq LAN config
          ansible.builtin.copy:
            dest: /etc/dnsmasq.d/lan.conf
            owner: root
            group: root
            mode: '0644'
            content: |
              interface={{ lan_interface }}
              bind-interfaces
              dhcp-range={{ dhcp_range_start }},{{ dhcp_range_end }},{{ lan_netmask }},12h
              dhcp-option=3,{{ router_lan_ip }}
              dhcp-option=6,8.8.8.8,8.8.4.4

        - name: Restart dnsmasq
          ansible.builtin.service:
            name: dnsmasq
            state: restarted
            enabled: true

  handlers:
    - name: Save iptables
      ansible.builtin.shell: |
        iptables-save > /etc/iptables/rules.v4
        netfilter-persistent save

#########################################################
# Play 2: Point LAN hosts (server, zabbix) to the router#
#########################################################
#- name: Set default route on LAN hosts via router
#  hosts: server,zabbix
#  become: true
#  gather_facts: true

#  vars:
#    router_host: "{{ groups['router'][0] }}"
#    router_lan_ip: "{{ hostvars[router_host]['router_lan_ip'] | default('') }}"
#    lan_iface: "{{ ansible_default_ipv4.interface }}"

#  tasks:
#    - name: Ensure iproute2 is installed
#      ansible.builtin.package:
#        name: iproute2
#        state: present

#    - name: Set default route via router
#      ansible.builtin.command: >
#        ip route replace default via {{ router_lan_ip }} dev {{ lan_iface }}
#      changed_when: true

#    - name: Persist default route with netplan
#      ansible.builtin.copy:
#        dest: /etc/netplan/98-default-route.yaml
#        mode: '0644'
#        content: |
#          network:
#            version: 2
#            ethernets:
#              {{ lan_iface }}:
#                dhcp4: true
#                routes:
#                  - to: 0.0.0.0/0
#                    via: {{ router_lan_ip }}
#      register: netplan_file

#    - name: Apply netplan
#      ansible.builtin.command: netplan apply
#      when: netplan_file is changed
#      changed_when: true

###############################################
# Play 3: Connectivity smoke tests
###############################################
- name: Connectivity checks
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Ping router LAN IP
      ansible.builtin.shell: "ping -c1 {{ hostvars[groups['router'][0]]['router_lan_ip'] }}"
      register: ping_r
      ignore_errors: true

    - name: Show result
      ansible.builtin.debug:
        var: ping_r.rc

