---
- name: Configure central rsyslog server on group 'server'
  hosts: zabbix
  become: true
  vars:
    rsyslog_protocol: tcp      # or udp
    rsyslog_port: 514
  tasks:
    - name: Ensure apt cache is up-to-date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Ensure directory for remote logs exists
      file:
        path: /var/log/remote
        state: directory
        owner: root
        group: adm
        mode: "0755"




    - name: Deploy rsyslog server config
      copy:
        dest: /etc/rsyslog.d/10-remote.conf
        content: |
         # module(load="imuxsock")
         # module(load="imklog")
          module(load="imudp")
          input(type="imudp" port="{{ rsyslog_port }}")
          module(load="imtcp")
          input(type="imtcp" port="{{ rsyslog_port }}")

          template(name="RemoteLogs" type="string" string="/var/log/remote/%HOSTNAME%.log")
          if ($fromhost-ip != '127.0.0.1' and $fromhost-ip != '::1') then {
            action(type="omfile" dynaFile="RemoteLogs")
            stop
          }
      notify: Restart rsyslog






    - name: logrotate for remote logs
      copy:
        dest: /etc/logrotate.d/remote-logs
        content: |
          /var/log/remote/*/*.log {
              daily
              missingok
              rotate 14
              compress
              delaycompress
              notifempty
              create 0640 root adm
              sharedscripts
              postrotate
                  /usr/lib/rsyslog/rsyslog-rotate || true
              endscript
          }

    - name: Check if ufw present
      stat:
        path: /usr/sbin/ufw
      register: ufw_stat

    - name: Allow rsyslog port via ufw when ufw exists
      community.general.ufw:
        rule: allow
        port: "{{ rsyslog_port }}"
        proto: "{{ rsyslog_protocol }}"
        comment: "Allow rsyslog remote logging"
      when: ufw_stat.stat.exists

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: true

- name: Configure rsyslog clients on groups 'router' and 'zabbix'
  hosts: router,server
  become: true
  vars:
    rsyslog_protocol: tcp
    rsyslog_port: 514
    rsyslog_server_ip: "{{ hostvars[groups['server'][0]].ansible_host | default(groups['server'][0]) }}"
  tasks:
    - name: Ensure apt cache is up-to-date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

#    - name: Deploy client forwarding config (forward all logs)
#      copy:
#        dest: /etc/rsyslog.d/60-forward.conf
#        content: |
#          # Forward all logs to central rsyslog server
#          action(type="omfwd"
#                 target="{{ rsyslog_server_ip }}"
#                 port="{{ rsyslog_port }}"
#                 protocol="{{ 'tcp' if rsyslog_protocol == 'tcp' else 'udp' }}"
#                 queue.type="LinkedList"
#                 queue.size="10000"
#                 queue.dequeueBatchSize="1000"
#                 action.resumeRetryCount="-1"
#                 template="RSYSLOG_ForwardFormat")
#      notify: Restart rsyslog

    - name: Ensure forward config exists
      copy:
        dest: /etc/rsyslog.d/60-forward.conf
        content: |
          *.* @{{ rsyslog_server_ip }}:{{ rsyslog_port }}
      notify: Restart rsyslog



    - name: Ensure RSYSLOG_ForwardFormat is default forward template
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^\$ActionForwardDefaultTemplate'
        line: '$ActionForwardDefaultTemplate RSYSLOG_ForwardFormat'
        state: present
        insertafter: EOF

    - name: Check if ufw present
      stat:
        path: /usr/sbin/ufw
      register: ufw_stat

    - name: Allow egress to rsyslog server via ufw when ufw exists
      community.general.ufw:
        rule: allow
        to_ip: "{{ rsyslog_server_ip }}"
        port: "{{ rsyslog_port }}"
        proto: "{{ rsyslog_protocol }}"
        comment: "Allow rsyslog forwarding to central server"
      when: ufw_stat.stat.exists

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: true

